# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sgdjs
email: simon@sgdjs.net
description: > # this means to ignore newlines until "baseurl:"
    Hub for sgdjs activity on the web
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hub.sgdjs.net" # the base hostname & protocol for your site
twitter_username: _gdjs
github_username:  sgdjs

# Build settings
markdown: kramdown
